---
- name: Wait for connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure VM is available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
    - name: Make sure SSH port is available
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        delay: 10
        timeout: 300
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

- name: Install packages and start Jenkins
  hosts: all
  become: true
  tasks:
    - name: Amazon Linux tasks
      include_tasks:
        file: tasks_amazon_linux.yaml
      when: ansible_facts.distribution == "Amazon"
    - name: Ubuntu tasks
      include_tasks:
        file: tasks_ubuntu.yaml
      when: ansible_facts.distribution == "Ubuntu"
    - name: add Jenkins user to Docker group
      user:
        name: jenkins
        groups: 
          - docker
        append: true
      when: not run_container
    - name: make sure Docker is running
      systemd:
        state: started
        name: docker
    - name: make sure Jenkins is running
      when: not run_container
      systemd:
        state: started
        name: jenkins
    - name: make sure Jenkins container is running
      when: run_container
      docker_container:
        name: jenkins
        ports:
        - "8080:8080"
        - "50000:50000"
        detach: true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/bin/docker
        - jenkins_home:/var/jenkins_home
        image: jenkins/jenkins:lts