---
- name: Wait for connection
  hosts: all
  tasks:
    - name: Make sure VM is available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
    - name: Make sure SSH port is available
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        delay: 10
        timeout: 300
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

- name: Install packages and start Jenkins
  hosts: all
  become: true
  tasks:
  - name: Add Jenkins repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import a key file from Jenkins-CI to enable installation from the package
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: Install the latest version of Java
    dnf:
      name: java-11-amazon-corretto
      state: latest
  - name: create jenkins user
    user:
      name: jenkins
  - name: Install a list of packages
    yum:
      name:
        - nodejs
        - docker
        - jenkins
      state: present
      update_cache: true
  - name: add Jenkins user to Docker group
    user:
      name: jenkins
      groups: 
        - docker
      append: true
  - name: Make sure a Docker is running
    systemd:
      state: started
      name: docker
  - name: Make sure a Jenkins is running
    systemd:
      state: started
      name: jenkins