---
- name: Wait for connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure VM is available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
    - name: Make sure SSH port is available
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        delay: 10
        timeout: 300
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

- name: Install packages and start Jenkins
  hosts: all
  become: true
  tasks:
    - name: Amazon Linux tasks
      include_tasks:
        file: tasks_amazon_linux.yaml
      when: ansible_facts.distribution == "Amazon"
    - name: Ubuntu tasks
      include_tasks:
        file: tasks_ubuntu.yaml
      when: ansible_facts.distribution == "Ubuntu"