apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: my-app
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.2
        ports:
        - containerPort: 80
        env:
        - name: PMA_USER
          value: app-user
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: db_url
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: my-app
spec:
  selector:
    app.kubernetes.io/name: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
