    - name: make sure Java is installed
      become: true
      apt:
        name: openjdk-17-jre
        state: present
        update_cache: yes
    - name: Check if prev app is running
      shell: ps aux | grep "[j]ava -jar" | awk '{print $2}'
      register: running_processes
    - name: Kill prev run app
      become: true
      command:
        cmd: kill {{running_processes.stdout}}
      when: running_processes.stdout != ""
    - name: Run new app
      shell: export DB_USER={{db_user}} && export DB_PWD={{db_password}} && export DB_NAME=java-app-db && export DB_SERVER={{db_server_ip}} && java -jar /home/ubuntu/java-app.jar
      async: 1000
      poll: 0