---
- name: Install Docker
  yum:
    name: docker
    state: present
    update_cache: true
- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  when: not run_container
- name: Import a key file from Jenkins-CI to enable installation from the package
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  when: not run_container
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  when: not run_container
- name: Install the latest version of Java
  dnf:
    name: java-11-amazon-corretto
    state: latest
  when: not run_container
- name: create jenkins user
  user:
    name: jenkins
  when: not run_container
- name: Install a list of packages
  yum:
    name:
      - nodejs
      - jenkins
    state: present
    update_cache: true
  when: not run_container