---
- name: Wait for connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure VM is available
      wait_for_connection:
        delay: 10
        timeout: 300
    - name: Make sure SSH port is available
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        delay: 10
        timeout: 300
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

- name: Install and configure MySQL server
  hosts: tag_Role_db_server
  become: true
  tasks:
    - name: Install MySQL
      yum:
        name: mysql-server
        state: present
        update_cache: yes
    - name: Start MySQL service
      service:
        name: mysqld
        state: started
    - name: Create DB 
      mysql_db:
        name: java-app-db
        state: present
    - name: Create DB user
      mysql_user:
        name: '{{db_user}}'
        password: '{{db_password}}'
        priv: 'java-app-db.*:ALL'
        state: present

- name: Install java-app
  hosts: tag_Role_web_app_server
  become: true
  tasks:
    - name: Clean-up prev build
      local_action: 
        module: command
        cmd: rm -rf /home/ec2-user/*
    - name: Checkout java-app repo
      git:
        repo: 'https://github.com/vlad-charle/ansible-practice.git'
        dest: /home/ec2-user/
    - name: Build locally
      local_action: 
        module: command
        chdir: /home/ec2-user/ansible-practice/web-app
        cmd: ./gradlew build
    - name: Copy to server
      copy:
        src: /home/ec2-user/ansible-practice/web-app/build/libs/bootcamp-java-mysql-project-1.0-SNAPSHOT.jar
        dest: /home/ec2-user/java-app.jar
    - name: Check if prev app is running
      shell: ps aux | grep "[j]ava -jar" | awk '{print $2}'
      register: running_processes
    - name: Kill prev run app
      command:
        cmd: kill {{running_processes.stdout}}
      when: running_processes.stdout != ""
    - name: Run new app
      command:
        cmd: java -jar /home/ec2-user/java-app.jar
      async: 1000
      poll: 0
