---
- name: Create namespace, configmap, secret, Docker creds
  hosts: localhost
  tasks:
    - name: Create a k8s ns
      k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: {{ kubeconfig }}
    - name: Create secret
      k8s:
        state: present
        kubeconfig: {{ kubeconfig }}
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mysql-secret
            namespace: my-app
          type: Opaque
          data:
            mysql-root-password: '{{ mysql_root_password|b64encode  }}'
            mysql-password: '{{ mysql_password|b64encode  }}'
            mysql-replication-password: '{{ mysql_replication_password|b64encode  }}'
    - name: Create configmap
      k8s: 
        state: present
        kubeconfig: {{ kubeconfig }}
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: my-app-config
            namespace: my-app
          data:
            db_url: mysql-release-primary.my-app.svc.cluster.local
    - name: Create Docker creds
      k8s:
        state: present
        kubeconfig: {{ kubeconfig }}
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: docker-hub
            namespace: my-app
          data:
            .dockerconfigjson: '{{ {"auths": {"https://index.docker.io/v1/": {"username": docker_username, "password": docker_password}}} | to_json | b64encode }}'
          type: kubernetes.io/dockerconfigjson
- name: Deploy DB
  hosts: localhost
  tasks:
    - name: Add Bitname chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        kubeconfig: {{ kubeconfig }}
        repo_url: "https://charts.bitnami.com/bitnami"
    - name: Deploy latest version of MySQL chart inside my-app namespace
      kubernetes.core.helm:
        name: mysql-release
        kubeconfig: {{ kubeconfig }}
        chart_ref: bitnami/mysql
        release_namespace: my-app
        values_files:
          - ../helm/mysql/values-mysql-bitnami.yaml
- name: Deploy app
  hosts: localhost
  tasks:
    - name: Deploy app
      k8s:
        state: present
        kubeconfig: {{ kubeconfig }}
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
            namespace: my-app
            labels:
              app: my-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                imagePullSecrets: 
                - name: docker-hub
                containers:
                - name: my-app
                  image: 'vladsanyuk/java-app:{{ image_tag }}'
                  ports:
                  - containerPort: 8080
                  env:
                  - name: DB_USER
                    value: app-user
                  - name: DB_PWD
                    valueFrom:
                      secretKeyRef:
                        name: mysql-secret
                        key: mysql-password
                  - name: DB_SERVER
                    valueFrom:
                      configMapKeyRef:
                        name: my-app-config
                        key: db_url
                  - name: DB_NAME
                    value: app-db
    - name: Deploy app service and other components
      k8s:
        state: present
        kubeconfig: {{ kubeconfig }}
        src: ../k8s/my-app.yaml